spring.application.name=DiagnoShare
# 1. The Database URL (Tells Spring where the database is and its name)
spring.datasource.url=jdbc:postgresql://localhost:5432/diagnoshare

# 2. Your PostgreSQL credentials
spring.datasource.username=postgres
spring.datasource.password=Gowtham@postgres

# 3. The JPA/Hibernate Magic (Crucial for our Entities)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true